version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - git clone https://github.com/flutter/flutter.git -b stable
      - export PATH="$PATH:`pwd`/flutter/bin"
      - sudo apt-get update
      - sudo apt-get install -y openjdk-17-jdk
      - update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1
      - update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
      - java -version 
      - wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O android-sdk.zip
      - unzip android-sdk.zip -d $HOME/android-sdk
      - export ANDROID_HOME=$HOME/android-sdk
      - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools
      - yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
      - sdkmanager --sdk_root=$ANDROID_HOME "platforms;android-33" "build-tools;33.0.0"
      - echo "Android SDK installed"
  build:
    commands:
      - echo "Building Flutter Web project"
      - flutter build apk --release

  post_build:
    commands:
      - echo "Uploading New Build Files To Your s3 Bucket"
      - aws s3 sync ./build/app/outputs/flutter-apk/ s3://codepipeline-us-east-1-648994628386/
      - echo "Creating CloudFront Cache Invalidation"
      - aws cloudfront create-invalidation --distribution-id YOUR-DISTRIBUTION-ID --paths "/*"
      - echo "Succesfully Deployed"
